# Generated by Django 5.2.16 on 2026-07-28 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import voice_agent_core.runtime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Herramienta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("habilitada", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Hook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.SlugField(max_length=60, unique=True)),
                ("habilitado", models.BooleanField(default=False)),
                ("orden", models.IntegerField(default=100)),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("transcripcion_lista", "transcripcion_lista"),
                            ("usuario_termino", "usuario_termino"),
                            ("respuesta_texto", "respuesta_texto"),
                            ("llamada_herramienta", "llamada_herramienta"),
                            ("resultado_herramienta", "resultado_herramienta"),
                            ("error", "error"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("ejecutar_comando", "ejecutar_comando"),
                            ("reescribir", "reescribir"),
                            ("vetar", "vetar"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comando", models.JSONField(blank=True, default=list)),
                ("entorno", models.JSONField(blank=True, default=dict)),
                ("timeout_secs", models.FloatField(default=5.0)),
                ("bloqueante", models.BooleanField(default=False)),
                ("patron", models.CharField(blank=True, max_length=500)),
                ("reemplazo", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ServidorMCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.SlugField(max_length=60, unique=True)),
                ("habilitado", models.BooleanField(default=False)),
                (
                    "transporte",
                    models.CharField(
                        choices=[("stdio", "stdio"), ("http", "http"), ("sse", "sse")],
                        default=voice_agent_core.runtime.TransporteMCP["STDIO"],
                        max_length=10,
                    ),
                ),
                ("comando", models.CharField(blank=True, max_length=500)),
                ("argumentos", models.JSONField(blank=True, default=list)),
                (
                    "entorno",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Admite ${VARIABLE}: la resuelve el agente, así el panel no ve el secreto.",
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500)),
                ("cabeceras", models.JSONField(blank=True, default=dict)),
                (
                    "herramientas_permitidas",
                    models.JSONField(
                        blank=True, default=list, help_text="Vacío significa todas las que ofrezca."
                    ),
                ),
                ("timeout_secs", models.FloatField(default=20.0)),
                ("ultimo_sondeo", models.DateTimeField(blank=True, null=True)),
                ("ultimo_error", models.TextField(blank=True)),
                ("herramientas_descubiertas", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="AjusteAgente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField(help_text="El valor serializado como JSON.")),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["clave"],
            },
        ),
        migrations.CreateModel(
            name="Despliegue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("exportado", "Exportado"),
                            ("reiniciado", "Exportado y reiniciado"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detalle", models.TextField(blank=True)),
                ("instantanea_settings", models.JSONField(default=dict)),
                ("instantanea_runtime", models.JSONField(default=dict)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="VersionPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "mensaje",
                    models.CharField(
                        blank=True, help_text="Qué cambiaste y por qué.", max_length=200
                    ),
                ),
                ("prompt_sistema", models.TextField()),
                (
                    "alma",
                    models.TextField(
                        blank=True,
                        help_text="Personalidad y tono. Se añade al final del prompt del sistema.",
                    ),
                ),
                ("saludo_inicial", models.TextField()),
                ("muletillas", models.JSONField(default=dict)),
                ("activa", models.BooleanField(default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("activa", True)),
                        fields=("activa",),
                        name="una_sola_version_activa",
                    )
                ],
            },
        ),
    ]
