# Generated by Django 5.2.16 on 2026-08-06 02:42

from django.db import migrations, models

import voice_agent_core.tareas


class Migration(migrations.Migration):
    dependencies = [
        ("voice_agent_panel", "0003_perfiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="TareaProgramada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.SlugField(
                        help_text="Identificador estable; nombra la carpeta de resultados.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=120)),
                ("habilitada", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("sala", "sala"), ("llamada", "llamada")],
                        default=voice_agent_core.tareas.TipoTarea["SALA"],
                        max_length=10,
                    ),
                ),
                ("cron", models.CharField(max_length=100)),
                ("mision", models.TextField()),
                ("guardar_respuestas", models.BooleanField(default=False)),
                ("contacto_nombre", models.CharField(blank=True, max_length=120)),
                ("contacto_numero", models.CharField(blank=True, max_length=40)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
