# Generated by Django 5.2.16 on 2026-08-12 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_agent_panel", "0004_tareaprogramada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LanzamientoCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[("lanzado", "Lanzado"), ("error", "No se pudo lanzar")],
                        max_length=20,
                    ),
                ),
                ("detalle", models.TextField(blank=True)),
                ("escenarios", models.JSONField(default=list)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="RevisionCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("id_ejecucion", models.CharField(max_length=120, unique=True)),
                (
                    "veredicto",
                    models.CharField(
                        choices=[("aprobado", "Aprobado"), ("fallo", "Fallo")], max_length=20
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-actualizado_en"],
            },
        ),
    ]
