# Generated by Django 5.2.16 on 2026-08-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_agent_panel", "0005_lanzamientocalidad_revisioncalidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="tareaprogramada",
            name="procedimiento",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
